Repository 10up/insert-special-characters, pull requests merged in 2019-09, with the labels that each got.

#42 fix credits.md link in readme.md
  README.md
Labels: bug, documentation

#44 Add the keyboard shortcut to docs
  README.md
  readme.txt
Labels: documentation

#41 Fixes for Firefox
  src/insert-special-characters.js
Labels: bug

#43 Release version 1.0.1
  CHANGELOG.md
  CONTRIBUTING.md
  CREDITS.md
  insert-special-characters.php
  package.json
  readme.txt
Labels: documentation

#46 Fix broken link in readme.txt
  readme.txt
Labels: bug, documentation
